code/community/Codisto/Sync/Controller/Router.php
code/community/Codisto/Sync/controllers/CodistoController.php

- Add ability to link to Codisto admin endpoints from external URLs
- Also passes on the "action" querystring value to the Codisto UI frame

Allow for external linking to Codisto Admin views

---

code/community/Codisto/Sync/Model/Sync.php
code/community/Codisto/Sync/controllers/SyncController.php

makes sure productoption/productoptionvalue data is sync'ed in the single product edit case

further fixes to productoption/productoptionvalue sequencing

---

code/community/Codisto/Sync/Model/Sync.php
code/community/Codisto/Sync/controllers/SyncController.php

make short description available as {ShortDescription} in description editor

start synchronising short description

---

code/community/Codisto/Sync/Controller/Router.php

previously, we used Mage::getBaseURL, however, it is more appropriate to use the current in flight request HTTP_HOST values

Use current request state for url values

---

code/community/Codisto/Sync/controllers/SyncController.php

provides a more bullet proof method by doing CREATE TABLE AS instead of copy then DELETE

adjust how templateread action is calculated

---

README.md

Remove reference to Magento 2.0 repo and be more explicit about our php compatibility

- Update README

---

code/community/Codisto/Sync/Model/Sync.php

also pass Short Description through the cms tag replacer

handling missing description field

---

code/community/Codisto/Sync/Controller/BaseController.php
code/community/Codisto/Sync/Controller/Router.php
code/community/Codisto/Sync/Model/Indexer/Ebay.php
code/community/Codisto/Sync/Model/Observer.php
code/community/Codisto/Sync/Model/Sync.php
code/community/Codisto/Sync/controllers/IndexController.php
code/community/Codisto/Sync/controllers/SyncController.php
code/community/Codisto/Sync/etc/config.xml

sync enhancements

---

code/community/Codisto/Sync/Controller/Router.php
code/community/Codisto/Sync/Model/Observer.php
code/community/Codisto/Sync/Model/Sync.php
code/community/Codisto/Sync/controllers/IndexController.php
code/community/Codisto/Sync/controllers/SyncController.php
code/community/Codisto/Sync/data/codisto_setup/data-install-1.1.19.php
code/community/Codisto/Sync/etc/config.xml

automatically invoice orders that are marked paid
allow order payment date and shipment date along with tracking numbers to participate in sync

track order data

---

code/community/Codisto/Sync/Model/Sync.php
code/community/Codisto/Sync/controllers/SyncController.php

add exception handling to sync end point

fix hard coded region table name

---

code/community/Codisto/Sync/controllers/IndexController.php

sub total should not have any tax nor freight
tax should not have tax on freight

fix order totals

---

code/community/Codisto/Sync/Controller/Router.php
code/community/Codisto/Sync/Model/Sync.php

fix querystring construction in router

---

.travis.yml
README.md
Test/Config/AdminHtml.php
Test/Config/Config.php
Test/Controller/Router.php
Test/Controllers/CodistoController.php
Test/Controllers/IndexController.php
Test/Controllers/SyncController.php

- Show travis-ci test status badges

- Fix travis-ci tests

---

code/community/Codisto/Sync/Model/Sync.php
code/community/Codisto/Sync/controllers/SyncController.php

-add fallback for null order state
-add more context to error messages

null order state fallback and improved error messages

---

code/community/Codisto/Sync/Controller/Router.php
code/community/Codisto/Sync/data/codisto_setup/data-install-1.1.42.php

only useful when this is merged and released https://github.com/ontech/killela/pull/145

fix detection of PDO sqlite driver to not crash when not present

---

.travis.yml

- without hardcoding to a specific php version

 - Attempt to update composer before anything is installed 

---

code/community/Codisto/Sync/data/codisto_setup/data-install-1.1.43.php

this stops synchronisation from triggering an installation flow

inhibit synchronisation calls from activating plugin installation flow

---

code/community/Codisto/Sync/Model/Indexer/Ebay.php

as reported by https://www.thinksoftware.net.au/

add Mage_CatalogInventory_Model_Stock_Item to indexer

---

code/community/Codisto/Sync/controllers/IndexController.php

create flatrate shipping address quote rate on no cart rates

fix setState -> setStatus

---

code/community/Codisto/Sync/controllers/IndexController.php

move away from importData on payment object

fix isPickup -> $isPickup

---

code/community/Codisto/Sync/Model/Sync.php
code/community/Codisto/Sync/controllers/SyncController.php

honour special_from_date, special_to_date
honour image excluded
process custom options -> productquestion/productquestionanswer sync tables

improve sync

---

code/community/Codisto/Sync/controllers/IndexController.php

Also ensure complete orders can't transition back to processing

Set order state and status. Read status for logic

---

code/community/Codisto/Sync/data/codisto_setup/data-install-1.1.69.php

- Improve lock timeout and make sure to clear the current config after saving.
- Don't report lock contention back to Codisto in install phase for subsequent requests.

Lock and configuration improvements for installation

---

code/community/Codisto/Sync/Helper/Data.php
code/community/Codisto/Sync/Model/Sync.php

only collecttotals on addresses to avoid dispatching checkout level events

use php ini in sub processes to ensure curl and pdo are loaded

---

code/community/Codisto/Sync/controllers/IndexController.php

this resolves freight totals being reverted to $0 on order creation

go back to previous strategy of forcing totals in order create

---

code/community/Codisto/Sync/Helper/Data.php
code/community/Codisto/Sync/Model/Indexer/Ebay.php
code/community/Codisto/Sync/Model/Sync.php

better php ini detection on sub process execution
incremental sync honours single store mode correctly
run text attribute values through cms processor

incremental sync improvements

---

code/community/Codisto/Sync/Helper/Data.php
code/community/Codisto/Sync/Model/Indexer/Ebay.php
code/community/Codisto/Sync/Model/Sync.php

only process cms content if a cms tag is present
if in single store mode signal against the signal store
better sub process launching and detection of loaded extensions in child

redo sync enhancements

---

code/community/Codisto/Sync/Controller/Router.php
code/community/Codisto/Sync/Helper/Data.php
code/community/Codisto/Sync/Model/Indexer/Ebay.php
code/community/Codisto/Sync/Model/Observer.php
code/community/Codisto/Sync/Model/Sync.php
code/community/Codisto/Sync/controllers/IndexController.php
code/community/Codisto/Sync/controllers/SyncController.php
code/community/Codisto/Sync/data/codisto_setup/data-install-1.1.94.php
code/community/Codisto/Sync/etc/config.xml

* explicitly close PDO cursors for older versions of PDO/sqlite
* shift temporary files from <MAGE_DIR>/var/ to <MAGE_DIR>/var/codisto/
* bug fix on attribute text - handle multi-select / array based attribute values
* optimise attribute extraction
* add missing extra order fields such as weight and invoiced totals
* start updating order addresses on order sync

batch of changes based on client feedback

---

code/community/Codisto/Sync/Controller/Router.php
code/community/Codisto/Sync/Helper/Data.php
code/community/Codisto/Sync/Model/Sync.php
code/community/Codisto/Sync/controllers/IndexController.php
code/community/Codisto/Sync/controllers/SyncController.php

more fixes to auth in router to work around early session instantiation
ensure incremental syncs push to the correct sync db in single store setup

stopped session creation during sync

---

code/community/Codisto/Sync/Model/Observer.php
code/community/Codisto/Sync/controllers/IndexController.php

inhibit double amounts in payment records

fix use of merchantid array in stock signal handler

---

code/community/Codisto/Sync/Model/Sync.php

don't skip attribute sync if store label is not present

fix lookup of store label attribute

---

code/community/Codisto/Sync/Helper/Data.php
code/community/Codisto/Sync/controllers/IndexController.php

recover from corrupted lock file

stop double pay event

---

code/community/Codisto/Sync/Helper/Signal.php
code/community/Codisto/Sync/Model/Observer.php

shift signal timeouts to codisto.log
ensure payment method object is available and can retrieve code before using it

fixes for issues reported by wowstores

---

code/community/Codisto/Sync/Helper/Data.php
code/community/Codisto/Sync/Model/Sync.php
code/community/Codisto/Sync/controllers/IndexController.php
code/community/Codisto/Sync/controllers/SyncController.php
code/community/Codisto/Sync/sql/codisto_setup/mysql4-install-1.90.15.php

ignore entity_type_id in attribute query
handle more corruption issues in nonce db

add codisto merchantid to order sync lookup

---

code/community/Codisto/Sync/Model/Sync.php
code/community/Codisto/Sync/etc/config.xml

html_entity_decode more string values and pass full flags to decode

switch name of payment method model string to avoid conflicts

---

code/community/Codisto/Sync/Helper/Data.php
code/community/Codisto/Sync/Model/Sync.php
code/community/Codisto/Sync/controllers/SyncController.php

add event timestamps on change tables to fairly prioritise

fix incremental sync responses to have incremental prepended
